name: Deploy to Dev Server

on:
    push:
        branches:
            - develop

jobs:
    setup_and_run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Node.jobs
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: build assets
              run: pnpm run build
