name: Deploy to Dev Server

on:
    push:
        branches:
            - develop

jobs:
    setup_and_run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: build assets
              run: pnpm run build

            - name: Check dist
              run: ls -la dist/

            - name: Deploy via FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.DEV_FTP_SERVER }}
                  username: ${{ secrets.DEV_FTP_USERNAME }}
                  password: ${{ secrets.DEV_FTP_PASSWORD }}
                  local-dir: ./dist/
                  server-dir: /home/sakaki-keita/
                  dangerous-clean-slate: false
                  exclude: |
                      **/.git*
                      **/.git*/**
                      **/node_modules/**
